stages:
  - build

variables:
  IMAGE: "192.168.10.248:5050/root/color-ai-backend"
  DOCKER_HOST: "unix:///var/run/docker.sock"

build:
  stage: build
  tags:
    - color-ai
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"192.168.10.248:5050\":{\"auth\":\"$(echo -n root:${GITLAB_PAT} | base64)\"}}}" > ~/.docker/config.json
  script:
    - docker build -t ${IMAGE}:${CI_COMMIT_SHORT_SHA} -t ${IMAGE}:latest .
    - docker push ${IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${IMAGE}:latest
